export const produtList = [
  {
    id: 1,
    image: "/assets/images/product-one.png",
    name: "Head Phones",
    price: 79,
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.",
  },
  {
    id: 2,
    image: "/assets/images/product-two.png",
    name: "Watch",
    price: 80,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 3,
    image: "/assets/images/product-three.png",
    name: "Home",
    price: 85,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 4,
    image: "/assets/images/product-four.png",
    name: "Fan",
    price: 20,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 5,
    image: "/assets/images/product-one.png",
    name: "Head Phones",
    price: 30,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 6,
    image: "/assets/images/product-two.png",
    name: "Watch",
    price: 40,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 7,
    image: "/assets/images/product-three.png",
    name: "Home",
    price: 50,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 8,
    image: "/assets/images/product-four.png",
    name: "Fan",
    price: 15,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 9,
    image: "/assets/images/product-one.png",
    name: "Head Phones",
    price: 10,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 10,
    image: "/assets/images/product-two.png",
    name: "Watch",
    price: 12,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 11,
    image: "/assets/images/product-three.png",
    name: "Home",
    price: 12,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 12,
    image: "/assets/images/product-four.png",
    name: "Fan",
    price: 12,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 13,
    image: "/assets/images/product-one.png",
    name: "Head Phones",
    price: 12,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 14,
    image: "/assets/images/product-two.png",
    name: "Watch",
    price: 12,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 15,
    image: "/assets/images/product-three.png",
    name: "Home",
    price: 12,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
  {
    id: 16,
    image: "/assets/images/product-four.png",
    name: "Fan",
    price: 12,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia,",
  },
];
